### ISSUE TITLE
CEP CE prevents Fall Guys from opening

### ISSUE THREAD

**Issue by DriftBoneYT** [Owyn/CreativeExpansionPack#3]
When I open Install CEP CE or whatever it was called, it just says Fall Guys is running and nothing happens. I don't know if its either my cheap Windows 8 computer preventing this from working or if its some sort of bug in the files or code.

**Comment by Owyn** [comment]
first run it generates files that's why you have to wait

**Comment by DriftBoneYT** [comment]
How long do I wait, it feels pretty long (thats what she said)

**Comment by Owyn** [comment]
maybe some minutes? if you're sure it's stuck - just try again

**Comment by DriftBoneYT** [comment]
it took a little while but it worked, thanks :)
