### ISSUE TITLE
Could not load file or assembly 'Il2Cppmscorlib, Version=3.7.1.6, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

### ISSUE THREAD

**Issue by mrszlox** [Owyn/CreativeExpansionPack#7]
i follow [the video](https://www.youtube.com/watch?v=udtIrtJIaFQ&ab_channel=LucaFG)
but it isn't work and a file was generated
[preloader_20240202_154457_364.log](https://github.com/Owyn/CreativeExpansionPack/files/14136977/preloader_20240202_154457_364.log)
I would be grateful if you could help me!

**Comment by Owyn** [comment]
" Select All:" version is very old & long broken after multiple game updates, don't use it.

If you want a level loader - use FGTools: https://discord.gg/97U7A4pfUA

**Comment by mrszlox** [comment]
> " Select All:" version is very old & long broken after multiple game updates, don't use it.
> 
> If you want a level loader - use FGTools: https://discord.gg/97U7A4pfUA

thank you very much, now it is work
